CMAKE_MINIMUM_REQUIRED(VERSION 3.24)

PROJECT(lib7zip
  VERSION 4.0.0
  LANGUAGES CXX
)

SET(CMAKE_CXX_STANDARD 14)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

INCLUDE(GNUInstallDirs)

IF (APPLE)
  SET(CMAKE_MACOSX_RPATH 1)
  SET(CMAKE_PREFIX_PATH /usr/local)
ENDIF ()

IF (NOT CMAKE_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE "DEBUG")
  #SET(CMAKE_BUILD_TYPE "RELEASE")
  #SET(CMAKE_BUILD_TYPE "RELWITHDEBINFO")
  #SET(CMAKE_BUILD_TYPE "MINSIZEREL")
ENDIF ()

SET(SEVENZIP_SOURCE_DIR "${PROJECT_SOURCE_DIR}/third_party/7zip" CACHE STRING "Location of 7zip sources")
OPTION(LIB7ZIP_BUILD_SHARED_LIB "Build shared library" OFF)
OPTION(LIB7ZIP_ENABLE_TESTING "Enable testing" ${PROJECT_IS_TOP_LEVEL})
OPTION(LIB7ZIP_WARNING_AS_ERROR "Threat all compiler warnings as errors" ${PROJECT_IS_TOP_LEVEL})

IF (NOT IS_DIRECTORY ${SEVENZIP_SOURCE_DIR})
  MESSAGE(FATAL_ERROR "7zip source not found at ${SEVENZIP_SOURCE_DIR}. Please ensure git submodule is initialized: git submodule update --init --recursive")
ENDIF ()

IF (LIB7ZIP_WARNING_AS_ERROR)
  SET(CMAKE_COMPILE_WARNING_AS_ERROR ON)
ENDIF ()

ADD_SUBDIRECTORY(src)
IF (LIB7ZIP_ENABLE_TESTING)
  ADD_SUBDIRECTORY(test)
ENDIF ()

# Install
INSTALL(FILES README.md DESTINATION ${CMAKE_INSTALL_DOCDIR})
